[package]
name = "uzh-biomed-bot"
version = "0.1.0"
authors = ["Jan Nils Ferner <contact@jnferner.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
